# Generated by Django 4.2.7 on 2025-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_company_name',
            field=models.CharField(blank=True, default='ECOMMERCE INVENTORY', help_text='Company name to display on shipping labels', max_length=255),
        ),
    ]
