# Generated by Django 5.2.6 on 2025-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_shipping_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Your business/company name (appears at top of shipping labels)', max_length=255, verbose_name='Your Company Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_company_name',
            field=models.CharField(blank=True, default='', help_text='Shipping company you prefer to use (FedEx, UPS, DHL, etc.) - Optional', max_length=255, verbose_name='Preferred Shipping Company'),
        ),
    ]
