# Generated by Django 4.2.7 on 2026-01-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Upload your company logo for invoices', null=True, upload_to='company_logos/'),
        ),
    ]
