# Generated by Django 4.2.7 on 2025-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='processing', max_length=20),
        ),
    ]
